[build]
  command = """
    git clone https://github.com/flutter/flutter.git --depth 1 -b 3.32.7 $HOME/flutter &&
    export PATH="$PATH:$HOME/flutter/bin" &&
    flutter config --enable-web &&
    flutter pub get &&
    flutter build web
  """
  
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200